// Package models defines the core domain types for TrialTerminator.
// These structs are the "truth" of what a Task is — they are independent
// of storage (Postgres), transport (HTTP), or messaging (Redis).
// Keeping domain types here prevents import cycles and makes the codebase
// easier to test: any package can import models without pulling in DB drivers.
package models

import (
	"time"

	"github.com/google/uuid"
)

// TaskStatus represents the finite states a Task can be in.
// Using a named string type (not a plain string) means the compiler
// catches mistakes like passing a raw "pending" string where a TaskStatus
// is expected. This is a lightweight form of type safety in Go.
type TaskStatus string

const (
	// StatusPending means the task has been created and is waiting in the queue.
	StatusPending TaskStatus = "PENDING"

	// StatusInProgress means a worker has claimed the task and is running Playwright.
	// A task in this state has a locked_at timestamp and locked_by worker ID.
	StatusInProgress TaskStatus = "IN_PROGRESS"

	// StatusSuccess means the subscription was cancelled successfully.
	StatusSuccess TaskStatus = "SUCCESS"

	// StatusFailed means the last attempt failed, but retries remain (attempts < max_attempts).
	StatusFailed TaskStatus = "FAILED"

	// StatusRetry means the task is explicitly queued for another attempt.
	// The distinction from FAILED: FAILED is the result of an attempt,
	// RETRY is the intention to attempt again. This makes dashboards clearer.
	StatusRetry TaskStatus = "RETRY"

	// StatusDeadLetter means all retries are exhausted. The task requires
	// human review. A screenshot evidence file will be attached (Sprint 3).
	StatusDeadLetter TaskStatus = "DEAD_LETTER"
)

// Task is the central domain object of the entire system.
// Every sprint revolves around reading or mutating a Task.
//
// Struct tag note: `db:"column_name"` is used by pgx's pgxscan library
// to map SQL result columns to Go struct fields automatically.
// `json:"field_name"` controls how the struct serializes to/from HTTP JSON bodies.
type Task struct {
	// ID is the internal primary key — never exposed to users for enumeration safety.
	ID uuid.UUID `db:"id"            json:"id"`

	// IdempotencyKey is provided by the caller (frontend). If the same key is
	// sent twice, the second request returns the existing task — not an error,
	// not a duplicate. This is the contract that makes the API safe to retry.
	IdempotencyKey uuid.UUID `db:"idempotency_key" json:"idempotency_key"`

	// ServiceName identifies which Playwright script to run (e.g., "netflix", "spotify").
	ServiceName string `db:"service_name"    json:"service_name"`

	// UserEmail is the login credential for the subscription service.
	UserEmail string `db:"user_email"       json:"user_email"`

	// Status is the current state in the state machine.
	Status TaskStatus `db:"status"           json:"status"`

	// Attempts tracks how many times a worker has tried this task.
	// When Attempts == MaxAttempts and the task fails, it moves to DEAD_LETTER.
	Attempts    int `db:"attempts"         json:"attempts"`
	MaxAttempts int `db:"max_attempts"     json:"max_attempts"`

	// Payload stores service-specific inputs as raw JSON.
	// Example: {"account_id": "abc123", "reason": "too_expensive"}
	// Using *[]byte (pointer) so we can represent NULL in the DB as nil in Go.
	Payload []byte `db:"payload"          json:"payload,omitempty"`

	// ErrorMessage stores the last error from a failed attempt.
	// Useful for debugging dead-letter tasks without needing to read logs.
	ErrorMessage *string `db:"error_message"    json:"error_message,omitempty"`

	// EvidencePath is populated in Sprint 3: the relative path to a screenshot
	// file captured when a Playwright automation fails (e.g., UI changed).
	EvidencePath *string `db:"evidence_path"    json:"evidence_path,omitempty"`

	// Timestamps
	CreatedAt time.Time `db:"created_at"       json:"created_at"`
	UpdatedAt time.Time `db:"updated_at"       json:"updated_at"`

	// Heartbeat fields — used by the worker and the requeue goroutine in Sprint 2.
	// A worker sets LockedAt and LockedBy when it claims a task.
	// If LockedAt is older than a threshold and status is still IN_PROGRESS,
	// the task is considered abandoned (worker crashed) and returned to PENDING.
	LockedAt *time.Time `db:"locked_at"        json:"-"` // json:"-" hides this from API responses
	LockedBy *string    `db:"locked_by"        json:"-"`
}

// CreateTaskRequest is what the API client (frontend) sends in the request body.
// It's separate from Task so we never accidentally let callers set internal fields
// like Status or Attempts. The boundary between "what the user controls"
// and "what the system controls" is explicit in the type system.
type CreateTaskRequest struct {
	// IdempotencyKey must be generated by the client (UUID v4).
	// The client is responsible for generating it so it can be stable across retries:
	// if the HTTP request times out, the client retries with the SAME key.
	IdempotencyKey string `json:"idempotency_key"`

	ServiceName string `json:"service_name"`
	UserEmail   string `json:"user_email"`

	// Payload is optional extra data. The API accepts it as raw JSON
	// so we don't need to define a schema per service at this layer.
	Payload map[string]interface{} `json:"payload,omitempty"`
}
